sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
before install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run test --single-run
before_script:
  - npm install -g gulp-cli
  - npm install -g karma
  - npm install -g typescript
  - npm install
  - npm run build:esm
cache:
  apt: true
  npm: true
  directories:
    - node_modules
