sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
  chrome: beta
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
before install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
  - sh -e /etc/init.d/xvfb start
  - rm -rf node_modules/ngx-duality
install:
  - npm install -g gulp-cli
  - npm install -g karma
  - npm install -g typescript
  - npm install
script:
  - npm run tslint
  - npm run test
  - npm run build
cache:
  apt: true
  npm: true
  directories:
    - node_modules
