sudo: false
language: node_js
node_js:
  - "iojs"
  - "6"

jobs:
  fast_finish: true
    # lint code
    - stage: lint
      install: true
      script: npm run tslint
    # test
    - &test
      stage: test
      script: npm run test