sudo: false
language: node_js
node_js:
  - "6"
script:
  - npm install
  - npm run test
  - npm run build:esm
before_script:
  - npm install -g gulp-cli
cache:
  apt: true
  npm: true
  directories:
    - node_modules
